#ifndef _H__ERRORS
#define _H__ERRORS

enum error {
    ERROR_OK,

    ERROR_WGL,
    ERROR_WGL_CREATE_CONTEXT,
    ERROR_WGL_MAKE_CURRENT,
    ERROR_WGL_CHOOSE_PIXEL_FORMAT,
    ERROR_WGL_NO_SUITABLE_PIXEL_FORMAT,
    
    ERROR_WINGDI_CHOOSE_PIXEL_FORMAT,
    ERROR_WINGDI_SET_PIXEL_FORMAT,
    ERROR_WINGDI_DESCRIBE_PIXEL_FORMAT,

    ERROR_WIN32_REGISTER_CLASS,
    ERROR_WIN32_CREATE_WINDOW,

    ERROR_OPENGL,

    ERROR_INVALID_VALUE,

    ERROR_SHADER_COMPILATION,
    ERROR_SHADER_PROGRAM_LINKAGE
};

#endif